version: '3.9'

services:

  db:
    container_name: e-com_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432



  pgadmin:
    container_name: e-com_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db



  app:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 2326 --reload"
    volumes:
      - .:/app
    ports:
      - 2326:2326
    depends_on:
      - db
